/**
 * Chat-domain client DTOs: Conversation*, Chat*, Message*, Stream*, Action*,
 * Emote*, Document*, Memory*, MCP*, Share*. One slice of the ElizaClient type
 * surface, re-exported through client-types.ts.
 */

import type {
  CapabilityHandoffRequest,
  LinkedAccountProviderId,
} from "@elizaos/shared";
import type {
  ChatFailureKind,
  ChatTerminalFailure,
  ChatToolCallEvent,
  ChatTurnStatus,
} from "@elizaos/shared/contracts";
import type { NativeToolCallEvent } from "./client-types-cloud";
import type {
  ConversationMetadata,
  ConversationScope,
} from "./client-types-core";

// Single-source SSE chat contract lives in @elizaos/shared (#12409); re-exported
// here so existing `@elizaos/ui` `api` consumers keep their import path. Imported
// (not export-from) because `failureKind` fields below reference the type in this
// module's scope.
export type {
  ChatFailureKind,
  ChatTerminalFailure,
  ChatToolCallEvent,
  ChatTurnStatus,
};

// Conversations
export interface Conversation {
  id: string;
  title: string;
  roomId: string;
  metadata?: ConversationMetadata;
  createdAt: string;
  updatedAt: string;
}

export interface ConversationGreeting {
  text: string;
  agentName: string;
  generated: boolean;
  persisted?: boolean;
  localInference?: LocalInferenceChatMetadata;
}

export interface CreateConversationOptions {
  includeGreeting?: boolean;
  bootstrapGreeting?: boolean;
  lang?: string;
  metadata?: ConversationMetadata;
}

export type { ConversationMetadata, ConversationScope };

// ── A2UI Content Blocks (Agent-to-UI) ────────────────────────────────

/** A plain text content block. */
export interface TextBlock {
  type: "text";
  text: string;
}

/** An inline config form block — renders ConfigRenderer in chat. */
export interface ConfigFormBlock {
  type: "config-form";
  pluginId: string;
  pluginName?: string;
  schema: Record<string, unknown>;
  hints?: Record<string, unknown>;
  values?: Record<string, unknown>;
}

/** A UiSpec interactive UI block extracted from agent response. */
export interface UiSpecBlock {
  type: "ui-spec";
  spec: Record<string, unknown>;
  raw?: string;
}

/** Union of all content block types. */
export type ContentBlock = TextBlock | ConfigFormBlock | UiSpecBlock;

/** An image attachment to send with a chat message. */
export interface ImageAttachment {
  /** Base64-encoded image data (no data URL prefix). */
  data: string;
  mimeType: string;
  name: string;
  /**
   * Optional client-generated downscaled preview (base64, no prefix). The
   * server persists it separately and exposes it as the attachment's
   * `thumbnailUrl` so the chat tile loads a small image while the full
   * resolution opens in the lightbox.
   */
  thumbnail?: { data: string; mimeType: string };
  /**
   * The stored {@link Transcript} record id when this attachment is a saved
   * transcript — lets the chat tile re-open the rich, editable record.
   */
  transcriptId?: string;
}

/**
 * Media kind for a rendered message attachment. Values match `@elizaos/core`
 * `ContentType` so server payloads line up without pulling core into the
 * browser bundle.
 */
export type MessageAttachmentContentType =
  | "image"
  | "video"
  | "audio"
  | "document"
  | "link";

/**
 * A media attachment carried on a rendered chat message — either uploaded by
 * the user or generated by the agent. Mirrors the `@elizaos/core` `Media`
 * shape (id/url/contentType/title/description/source/text). `url` is a served
 * URL (`/api/media/<hash>`), a remote https URL, or a `data:` URL; the
 * renderer treats all three the same.
 */
export interface MessageAttachment {
  id: string;
  url: string;
  contentType?: MessageAttachmentContentType;
  title?: string;
  description?: string;
  source?: string;
  /** Readable extracted content (transcript / OCR / document text). */
  text?: string;
  /** MIME type when known, e.g. "image/png" or "application/pdf". */
  mimeType?: string;
  /** Downscaled preview URL for the inline tile; `url` is the full original. */
  thumbnailUrl?: string;
  /**
   * The stored {@link Transcript} record id when this attachment is a saved
   * transcript — the chat tile opens it in the maximized, editable viewer.
   */
  transcriptId?: string;
  /**
   * Reason the enrichment pass could not extract text/description (e.g. a
   * transcription backend being unavailable). Present only on a failed
   * enrichment; the tile surfaces it so a stored-but-unreadable attachment is
   * never silently indistinguishable from a genuinely empty one.
   */
  notProcessed?: string;
  /**
   * Present (true) when `url` is the server-selected PII-scrubbed variant of
   * the original attachment (#14781). Display-only: the server decides
   * redaction; the tile renders a redacted badge.
   */
  redacted?: true;
}

export interface ConversationMessageReaction {
  emoji: string;
  count: number;
  users?: string[];
}

export interface ChatActionResultSummary {
  actionName?: string;
  success: boolean;
  text?: string;
  error?: string;
  values?: Record<string, unknown>;
}

export type LocalInferenceChatStatus =
  | "missing"
  | "downloading"
  | "loading"
  | "failed"
  | "no_space"
  | "idle"
  | "ready"
  | "cancelled"
  | "routing";

export interface LocalInferenceChatMetadata {
  intent?:
    | "retry"
    | "resume"
    | "redownload"
    | "download"
    | "cancel"
    | "switch_smaller"
    | "status"
    | "use_cloud"
    | "use_local";
  status: LocalInferenceChatStatus;
  modelId?: string | null;
  activeModelId?: string | null;
  provider?: string;
  error?: string;
  progress?: {
    percent?: number;
    receivedBytes: number;
    totalBytes: number;
    bytesPerSec?: number;
    etaMs?: number | null;
  };
}

export type SensitiveRequestStatus =
  | "pending"
  | "saved"
  | "submitted"
  | "fulfilled"
  | "expired"
  | "cancelled"
  | "failed";

export interface SensitiveRequestDelivery {
  mode:
    | "inline_owner_app"
    | "cloud_authenticated_link"
    | "tunnel_authenticated_link"
    | "private_dm"
    | "public_link"
    | "dm_or_owner_app_instruction";
  instruction?: string;
  privateRouteRequired?: boolean;
  canCollectValueInCurrentChannel?: boolean;
  /**
   * Present only when this secret request collects a credential for a blocked
   * coding sub-agent. Identifiers only — the scoped token and the value are
   * NEVER serialized here. When set, `SensitiveRequestBlock` tunnels the value
   * to the waiting child via `client.tunnelCredential` instead of writing it to
   * the agent secret store (the two paths are mutually exclusive).
   */
  tunnel?: {
    credentialScopeId: string;
    childSessionId: string;
    keys?: readonly string[];
  };
}

export interface SensitiveRequestFormField {
  name: string;
  label?: string;
  input?: "secret" | "text" | "image" | "file";
  required?: boolean;
  /** For `input: "image" | "file"` — accepted MIME types (the `accept` attr). */
  mimeTypes?: string[];
  /** For `input: "image" | "file"` — max upload size in bytes. */
  maxBytes?: number;
}

/**
 * `kind: "secret"` — render a per-field password/text form (today's behavior).
 * `kind: "oauth"`  — render a single "Connect …" button that opens the
 * authorization URL in a popup; the actual token never flows through the
 * chat message stream. `fields` is unused for OAuth; the relevant fields are
 * `provider`, `scopes`, and `authorizationUrl`.
 * `kind: "remote_connect"` — render the same per-field text/secret form as
 * `secret`, but on submit dispatch the hardened `CONNECT_EVENT` (point the app
 * at a remote agent) instead of writing the values to the secret store. Used
 * by first-run to collect a remote agent's URL + access token inline.
 */
export interface SensitiveRequestForm {
  type: "sensitive_request_form";
  kind: "secret" | "oauth" | "remote_connect";
  mode: SensitiveRequestDelivery["mode"];
  fields: SensitiveRequestFormField[];
  submitLabel?: string;
  statusOnly?: boolean;
  /** OAuth-only: human-readable provider label (e.g. "GitHub"). */
  provider?: string;
  /** OAuth-only: scopes the consent screen will request. */
  scopes?: string[];
  /**
   * OAuth-only: the consent URL to open. The widget opens this in a popup
   * and never includes it in the rendered chat text. The OAuth callback
   * lands the token in the vault server-side; the widget polls the
   * `secretRequest.status` via `client.getSensitiveRequestStatus` (or
   * receives a fresh `secretRequest` on the next assistant turn).
   */
  authorizationUrl?: string;
}

export interface ConversationSecretRequest {
  key: string;
  reason?: string;
  status: SensitiveRequestStatus;
  delivery?: SensitiveRequestDelivery;
  form?: SensitiveRequestForm;
}

/**
 * Structured "connect another account" request emitted by the agent when the
 * user asks to add/log into an additional Claude or Codex account. The renderer
 * turns this into an inline entry point (per-provider count + "Add account")
 * that opens the existing, already-audited `AddAccountDialog` OAuth/API-key
 * flow — the block never manages accounts itself, it only offers a shortcut
 * into the canonical dialog. Round-trips on the assistant turn the same way
 * `failureKind` does so it survives a GET /messages reload.
 */
export interface AccountConnectRequest {
  /** Providers the user may connect a new account for (offer order preserved). */
  providers: LinkedAccountProviderId[];
  /** Optional short reason the agent surfaced this (e.g. "you asked to add a second Claude account"). */
  reason?: string;
}

export interface ConversationMessage {
  id: string;
  /**
   * UI-local row identity preserved when an optimistic id is rebound to its
   * durable server id. Never sent as the domain message identifier.
   */
  clientRenderId?: string;
  role: "user" | "assistant";
  text: string;
  timestamp: number;
  /** Machine-only assistant output excluded from the rendered transcript. */
  transcriptVisibility?: "internal";
  /** Structured content blocks (A2UI). When present, `text` is the fallback. */
  blocks?: ContentBlock[];
  /**
   * Media attached to this message — user uploads (images/audio/video/pdf) and
   * agent-generated media (images, audio clips). Rendered inline by
   * `MessageAttachments`. Sourced from the message's `content.attachments` on
   * the server and from the SSE `done` event for in-flight assistant turns.
   */
  attachments?: MessageAttachment[];
  /** Source channel when forwarded from another channel (e.g. "autonomy"). */
  source?: string;
  /** Short topic labels retained for search and memory semantics. */
  topics?: string[];
  /** Concrete action name that produced this assistant turn, when applicable. */
  actionName?: string;
  /** Callback/status lines emitted while the action was running. */
  actionCallbackHistory?: string[];
  /** Username of the sender (e.g. viewer username, discord username). */
  from?: string;
  /** Connector username/handle when available. */
  fromUserName?: string;
  /** Sender avatar URL when the connector can provide one. */
  avatarUrl?: string;
  /** Internal message id this message replies to, when available. */
  replyToMessageId?: string;
  /** Best-effort display name of the replied-to sender. */
  replyToSenderName?: string;
  /** Best-effort username/handle of the replied-to sender. */
  replyToSenderUserName?: string;
  /** Aggregated reactions attached to this message. */
  reactions?: ConversationMessageReaction[];
  /** True when the SSE stream was interrupted before receiving a "done" event. */
  interrupted?: boolean;
  /**
   * True while this in-flight assistant turn's visible text is an action-
   * callback delivery the turn's final reply may replace wholesale (server
   * marks those stream frames `provisional`). Text rendering treats it like
   * any streamed text; VOICE OUTPUT MUST NOT SPEAK IT — speech cannot be
   * retracted, and speaking the callback ack plus the final reply is the
   * voice "double-speak" defect. Cleared by the terminal reconciliation.
   */
  provisional?: boolean;
  /**
   * UI-local assistant reply with no durable server row. It remains visible so
   * the user can read the terminal failure, then retires when the next user turn
   * begins instead of surviving beneath a successful retry.
   */
  assistantEphemeral?: boolean;
  /**
   * Agent reasoning/thought for this turn, rendered as a collapsed-by-default
   * block separate from `text`. Sourced from the SSE `done` event's `thought`
   * field; absent when the model emitted no reasoning.
   */
  reasoning?: string;
  /**
   * Inline tool/action-call rows for this turn, accumulated live from the chat
   * SSE `tool` events (#13535): each `call` frame appends a running row and its
   * later `result`/`error` flips the same row (matched by `callId`) to
   * success/failure. Projected into `NativeToolCallEvent` so the thread reuses
   * the trajectory inspector's `ToolCallEventLog`. Absent when the turn ran no
   * tools.
   */
  toolEvents?: NativeToolCallEvent[];
  /**
   * When set, this assistant turn is the server's no-provider /
   * provider-issue / insufficient-credits fallback. The renderer can
   * substitute a structured gate UI (e.g. "Connect a provider →
   * Settings") for `failureKind === "no_provider"` instead of rendering
   * the fallback `text` as a normal reply bubble.
   */
  failureKind?: ChatFailureKind;
  /** Authoritative terminal failure details retained for retry and diagnostics. */
  terminalFailure?: ChatTerminalFailure;
  /** Structured local-inference status returned with local model command/error replies. */
  localInference?: LocalInferenceChatMetadata;
  /** Structured sensitive/private information request metadata. */
  secretRequest?: ConversationSecretRequest;
  /**
   * Structured "connect another account" request. When set, this assistant
   * turn offers to add another Claude/Codex account: the renderer substitutes
   * the `AccountConnectBlock` (per-provider count + "Add account" opening
   * `AddAccountDialog`) for the plain reply text.
   */
  accountConnect?: AccountConnectRequest;
  /** Validated Shared-to-personal setup receipt rendered as an in-chat CTA. */
  capabilityHandoff?: CapabilityHandoffRequest;
  /**
   * Voice speaker attribution carried back from the server when this turn was
   * captured via voice and R2's speaker-id pipeline labelled it. Populated by
   * the runtime's voice ingress path; absent for text turns and assistant
   * responses. Mirrors the `ChatVoiceSpeaker` shape consumed by the chat
   * renderer.
   */
  voiceSpeaker?: {
    entityId?: string;
    name?: string;
    userName?: string;
    isOwner?: boolean;
  };
}

/**
 * Runtime guard for a {@link ConversationMessage} — validates the four required
 * fields (`id`, `role`, `text`, `timestamp`) of an untrusted value before it is
 * trusted as a message. Server/connector responses (e.g. `sendInboxMessage`)
 * are appended straight into the rendered message list; a malformed payload
 * (missing id/role/timestamp, an unexpected role) must NOT be `as`-cast into
 * state where it breaks keying/rendering. Use this at the API boundary instead
 * of `value as ConversationMessage`.
 */
export function isConversationMessage(
  value: unknown,
): value is ConversationMessage {
  if (typeof value !== "object" || value === null) return false;
  const m = value as Record<string, unknown>;
  return (
    typeof m.id === "string" &&
    m.id.length > 0 &&
    (m.role === "user" || m.role === "assistant") &&
    typeof m.text === "string" &&
    typeof m.timestamp === "number" &&
    Number.isFinite(m.timestamp)
  );
}

/** One keyword-search hit from `GET /api/conversations/messages/search`. */
export interface ConversationMessageSearchResult {
  messageId: string;
  conversationId: string;
  roomId: string;
  role: "user" | "assistant";
  text: string;
  /** A `…keyword…` excerpt around the first match, for the result row. */
  snippet: string;
  createdAt: number;
  /** Relevance score (higher = better); the server sorts by it then recency. */
  score: number;
}

export interface ConversationMessageSearchResponse {
  results: ConversationMessageSearchResult[];
  count: number;
}

export type ConversationChannelType =
  | "DM"
  | "GROUP"
  | "VOICE_DM"
  | "VOICE_GROUP"
  | "API";

export interface ChatTokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  llmCalls?: number;
  model?: string;
}

// Document / Character Knowledge types
export interface DocumentStats {
  documentCount: number;
  fragmentCount: number;
  agentId: string;
}

export type DocumentScope =
  | "global"
  | "owner-private"
  | "user-private"
  | "agent-private";

export type DocumentProvenanceKind =
  | "import"
  | "upload"
  | "learned"
  | "character"
  | "url"
  | "youtube"
  | "bundled"
  | "unknown";

export interface DocumentProvenance {
  kind: DocumentProvenanceKind;
  label: string;
  detail?: string;
}

export interface DocumentRecord {
  id: string;
  filename: string;
  contentType: string;
  fileSize: number;
  createdAt: number;
  fragmentCount: number;
  scope?: DocumentScope;
  scopedToEntityId?: string;
  addedBy?: string;
  addedByRole?: "OWNER" | "ADMIN" | "USER" | "AGENT" | "RUNTIME";
  addedFrom?: string;
  source: DocumentProvenanceKind;
  url?: string;
  provenance: DocumentProvenance;
  canEditText: boolean;
  editabilityReason?: string;
  canDelete: boolean;
  deleteabilityReason?: string;
  content?: { text?: string };
  /** When this document mirrors a voice Transcript (#8789): the original
   *  transcript record id (the Knowledge view links back to it) + its audio. */
  transcriptId?: string;
  transcriptAudioUrl?: string;
}

export interface DocumentDetail extends DocumentRecord {
  content?: { text?: string };
}

export interface DocumentsResponse {
  documents: DocumentRecord[];
  total: number;
  limit: number;
  offset: number;
}

/**
 * Whole-store per-facet counts for the Knowledge hub segmented control
 * (#13594). Keyed by the coarse hub facet; `all` is the readable total under
 * the current scope/room/search narrowing.
 */
export interface DocumentFacetCountsResponse {
  counts: {
    all: number;
    doc: number;
    image: number;
    audio: number;
    video: number;
    transcript: number;
  };
}

export interface DocumentFragmentRecord {
  id: string;
  text: string;
  position?: number;
  createdAt: number;
}

export interface DocumentFragmentsResponse {
  documentId: string;
  fragments: DocumentFragmentRecord[];
  count: number;
}

export interface DocumentSearchResult {
  id: string;
  text: string;
  similarity: number;
  documentId?: string;
  documentTitle?: string;
  documentProvenance?: DocumentProvenance;
  position?: number;
  transcriptId?: string;
  startMs?: number;
  endMs?: number;
}

export interface DocumentSearchResponse {
  query: string;
  threshold: number;
  results: DocumentSearchResult[];
  count: number;
}

export interface DocumentUploadResult {
  ok: boolean;
  documentId: string;
  fragmentCount: number;
  filename?: string;
  contentType?: string;
  isYouTubeTranscript?: boolean;
  warnings?: string[];
}

export interface DocumentUpdateResult {
  ok: boolean;
  documentId: string;
  fragmentCount: number;
}

export interface DocumentBulkUploadItemResult {
  index: number;
  ok: boolean;
  filename: string;
  documentId?: string;
  fragmentCount?: number;
  error?: string;
  warnings?: string[];
}

export interface DocumentBulkUploadResult {
  ok: boolean;
  total: number;
  successCount: number;
  failureCount: number;
  results: DocumentBulkUploadItemResult[];
}

// Memory / context command types
export interface MemorySearchResult {
  id: string;
  text: string;
  createdAt: number;
  score: number;
}

export interface MemorySearchResponse {
  query: string;
  results: MemorySearchResult[];
  count: number;
  limit: number;
}

export interface MemoryRememberResponse {
  ok: boolean;
  id: string;
  text: string;
  createdAt: number;
}

export interface QuickContextResponse {
  query: string;
  answer: string;
  memories: MemorySearchResult[];
  documents: DocumentSearchResult[];
}

// Memory Viewer types
export interface MemoryBrowseItem {
  id: string;
  type: string;
  text: string;
  entityId: string | null;
  roomId: string | null;
  agentId: string | null;
  createdAt: number;
  metadata: Record<string, unknown> | null;
  source: string | null;
}

export interface MemoryBrowseQuery {
  type?: string;
  entityId?: string;
  /** Comma-joinable entity IDs for multi-identity people. */
  entityIds?: string[];
  roomId?: string;
  q?: string;
  limit?: number;
  offset?: number;
}

export interface MemoryBrowseResponse {
  memories: MemoryBrowseItem[];
  /** Number of eligible rows observed while assembling this page. */
  total: number;
  /** Whether `total` is complete rather than a lower bound. */
  totalIsExact?: boolean;
  /** Whether another page is known to exist. */
  hasMore?: boolean;
  limit: number;
  offset: number;
}

export interface MemoryFeedQuery {
  type?: string;
  limit?: number;
  before?: number;
  /** ID tie-breaker paired with `before` for an exclusive stable cursor. */
  beforeId?: string;
}

export interface MemoryFeedResponse {
  memories: MemoryBrowseItem[];
  count: number;
  limit: number;
  hasMore: boolean;
}

export interface MemoryStatsResponse {
  total: number;
  byType: Record<string, number>;
}

// MCP
export interface McpServerConfig {
  type: "stdio" | "streamable-http" | "sse";
  command?: string;
  args?: string[];
  url?: string;
  env?: Record<string, string>;
  headers?: Record<string, string>;
}

export interface McpMarketplaceResult {
  name: string;
  description?: string;
  connectionType: string;
  npmPackage?: string;
  dockerImage?: string;
}

export interface McpRegistryServerDetail {
  packages?: Array<{
    environmentVariables: Array<{
      name: string;
      default?: string;
      isRequired?: boolean;
    }>;
    packageArguments?: Array<{ default?: string }>;
  }>;
  remotes?: Array<{
    type?: string;
    url: string;
    headers: Array<{ name: string; isRequired?: boolean }>;
  }>;
}

export interface McpServerStatus {
  name: string;
  connected: boolean;
  error?: string;
}

// Share Ingest
export interface ShareIngestPayload {
  title?: string;
  url?: string;
  text?: string;
  files?: Array<{ name: string }>;
}

export interface ShareIngestItem {
  suggestedPrompt: string;
  files: Array<{ name: string }>;
}

// ── Workflow types ────────────────────────────────────────────────────────────

export type WorkflowMode = "cloud" | "disabled";
export type WorkflowRuntimeStatus = "ready" | "error";

export interface WorkflowStatusResponse {
  mode: WorkflowMode;
  host: string | null;
  status: WorkflowRuntimeStatus;
  cloudConnected: boolean;
  localEnabled: boolean;
  platform?: "cloud";
  cloudHealth?: "healthy" | "unknown";
  engine: "smthrs";
}

export interface WorkflowStepManifest {
  id: string;
  label: string;
  kind:
    | "approval"
    | "branch"
    | "loop"
    | "parallel"
    | "sequence"
    | "signal"
    | "task"
    | "timer"
    | "ui"
    | "workflow";
  dependsOn?: string[];
  description?: string;
  agent?: string;
}

export interface WorkflowWidgetManifest {
  id: string;
  title: string;
  description?: string;
  surface: "chat" | "workflow" | "both";
  component:
    | "approval"
    | "chart"
    | "data-table"
    | "form"
    | "issue-list"
    | "json"
    | "markdown"
    | "status";
  dataPath?: string;
  actions?: Array<{
    id: string;
    label: string;
    signal?: string;
    style?: "default" | "primary" | "danger";
  }>;
}

export interface WorkflowDefinition {
  id: string;
  name: string;
  active: boolean;
  versionId: string;
  createdAt: string;
  updatedAt: string;
  description?: string;
  source: string;
  language: "tsx" | "typescript";
  inputSchema?: Record<string, unknown>;
  steps?: WorkflowStepManifest[];
  widgets?: WorkflowWidgetManifest[];
  schedule?: { cron: string; timezone: string; enabled: boolean };
  metadata?: Record<string, string | number | boolean>;
}

export type WorkflowRevisionOperation =
  | "update"
  | "activate"
  | "deactivate"
  | "tags"
  | "restore"
  | "delete";

export interface WorkflowRevision {
  id: string;
  workflowId: string;
  versionId: string;
  name: string;
  active: boolean;
  workflow?: WorkflowDefinition;
  createdAt: string;
  updatedAt: string;
  capturedAt: string;
  operation: WorkflowRevisionOperation;
}

export interface WorkflowRunEvent {
  id: string;
  sequence: number;
  runId: string;
  workflowId: string;
  timestamp: string;
  type: string;
  nodeId?: string;
  iteration?: number;
  payload: Record<string, unknown>;
}

export interface WorkflowApproval {
  runId: string;
  workflowId: string;
  nodeId: string;
  iteration: number;
  status: "pending" | "approved" | "denied";
  prompt?: string;
  requestedAt: string;
  decidedAt?: string;
  decidedBy?: string;
  decision?: unknown;
}

export interface WorkflowExecution {
  id: string;
  status:
    | "cancelled"
    | "continued"
    | "failed"
    | "finished"
    | "paused"
    | "queued"
    | "running"
    | "waiting-approval"
    | "waiting-event"
    | "waiting-quota"
    | "waiting-timer";
  finished: boolean;
  startedAt: string;
  stoppedAt?: string | null;
  mode: string;
  workflowId: string;
  workflowVersionId: string;
  workflowName: string;
  input: Record<string, unknown>;
  output?: unknown;
  error?: { message: string; stack?: string };
  events?: WorkflowRunEvent[];
  approvals?: WorkflowApproval[];
  parentRunId?: string | null;
  nextRunId?: string;
  idempotencyKey?: string;
}

export interface WorkflowEvaluationSampleNode {
  name: string;
  status: "success" | "error" | "unknown";
  itemCount: number;
  executionTimeMs?: number;
  error?: string;
  preview?: string;
}

export interface WorkflowEvaluationSample {
  id: string;
  workflowId: string;
  workflowName: string;
  workflowVersionId?: string;
  executionId: string;
  createdAt: string;
  input: {
    mode: string;
    triggerData?: Record<string, unknown>;
  };
  expected: {
    status: WorkflowExecution["status"];
    passed: boolean;
    lastNodeExecuted?: string;
    error?: string;
    nodes: WorkflowEvaluationSampleNode[];
  };
  score: {
    pass: boolean;
    value: number;
    reason: string;
  };
  tags: string[];
}

export interface WorkflowEvaluationSuite {
  workflowId: string;
  workflowName: string;
  workflowVersionId?: string;
  generatedAt: string;
  sampleCount: number;
  samples: WorkflowEvaluationSample[];
  jsonl: string;
  optimizer: {
    engine: "smithers-gepa";
    target: "workflow-generation";
    suiteName: string;
    caseFile: string;
    recommendedCommand: string;
    recommendedEvalCommand: string;
    recommendedOptimizeCommand: string;
    recommendedObservabilityCommand: string;
    recommendedMetricsCommand: string;
    notes: string[];
  };
}

export interface WorkflowDefinitionWriteRequest {
  name: string;
  description?: string;
  source: string;
  language: "tsx" | "typescript";
  active?: boolean;
  inputSchema?: Record<string, unknown>;
  steps?: WorkflowStepManifest[];
  widgets?: WorkflowWidgetManifest[];
  schedule?: { cron: string; timezone: string; enabled: boolean };
  metadata?: Record<string, string | number | boolean>;
}
