/** Exercises the canonical image transaction with byte-real in-memory R2 artifacts. */

import { describe, expect, test } from "bun:test";
import { ApiError } from "../api/cloud-worker-errors";
import type { ImageProvider } from "../providers/image/types";
import { putPublicObject } from "../storage/r2-public-object";
import type { RuntimeR2Bucket, RuntimeR2Object } from "../storage/r2-runtime-binding";
import { InsufficientCreditsError } from "./credits";
import {
  createImageGenerationExecutor,
  type ExecuteImageGenerationInput,
  type ImageGenerationAdmission,
  type ImageGenerationDependencies,
} from "./image-generation";

const PNG_BYTES = new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82]);

class MemoryR2Bucket implements RuntimeR2Bucket {
  readonly objects = new Map<string, Uint8Array>();
  readonly deleted: string[] = [];

  async get(key: string): Promise<RuntimeR2Object | null> {
    const bytes = this.objects.get(key);
    if (!bytes) return null;
    return {
      text: async () => new TextDecoder().decode(bytes),
      arrayBuffer: async () => bytes.slice().buffer,
    };
  }

  async put(
    key: string,
    value: string | ArrayBuffer | ArrayBufferView | Blob | null,
  ): Promise<void> {
    if (!ArrayBuffer.isView(value)) throw new Error("Memory R2 expected generated bytes");
    this.objects.set(key, new Uint8Array(value.buffer, value.byteOffset, value.byteLength).slice());
  }

  async delete(key: string): Promise<void> {
    this.deleted.push(key);
    this.objects.delete(key);
  }
}

function requestInput(
  bucket: MemoryR2Bucket,
  admit: ExecuteImageGenerationInput["admit"],
): ExecuteImageGenerationInput {
  return {
    input: { prompt: "A tiny orange lighthouse", numImages: 1 },
    actor: { organizationId: "org-1", userId: "user-1", apiKeyId: null },
    identity: { requestId: "image-request-1", source: "personal-shared" },
    bindings: { BLOB: bucket, R2_PUBLIC_HOST: "media.example.com" },
    providerKeys: { ATLASCLOUD_API_KEY: "configured" },
    admit,
  };
}

function successfulAdmission(events: string[]): ImageGenerationAdmission {
  return {
    reservation: {
      reservedAmount: 0.02,
      reservationTransactionId: "reservation-1",
      affiliateAttribution: null,
      affiliatePayoutSourceId: null,
      reconcile: async (cost) => {
        events.push(`settle:${cost}`);
        return null;
      },
    },
    settle: async (cost) => {
      events.push(`direct-settle:${cost}`);
      return null;
    },
    settleUnknown: async () => {
      events.push("settle-unknown");
      return null;
    },
    markProviderDispatched: async () => {
      events.push("dispatch");
    },
  };
}

function dependencies(
  events: string[],
  overrides: Partial<ImageGenerationDependencies> = {},
): ImageGenerationDependencies {
  const provider: ImageProvider = {
    billingSource: "atlascloud",
    generate: async () => {
      events.push("provider");
      return {
        dataUrl: "data:image/png;base64,iVBORw0KGgo=",
        bytes: PNG_BYTES,
        mimeType: "image/png",
        text: "A tiny orange lighthouse",
      };
    },
  };
  return {
    getProvider: () => provider,
    calculateCost: async () => {
      events.push("pricing");
      return {
        totalCost: 0.02,
        baseTotalCost: 0.016,
        platformMarkup: 0.004,
        matchedEntry: {
          billingSource: "atlascloud",
          provider: "google",
          model: "google/nano-banana-2/text-to-image",
          productFamily: "image",
          chargeType: "generation",
          unit: "image",
          unitPrice: 0.016,
          dimensions: {},
        },
      };
    },
    assertSafe: async ({ surface }) => {
      events.push(`safety:${surface}`);
    },
    putObject: async (bindings, options) => {
      events.push("r2-put");
      return await putPublicObject(bindings, options);
    },
    createGeneration: async () => {
      events.push("history");
      return { id: "generation-1" };
    },
    deleteGeneration: async (id) => {
      events.push(`history-delete:${id}`);
    },
    billFlat: async (_context, cost, reservation) => {
      events.push("bill");
      await reservation?.reconcile(cost.totalCost);
    },
    randomUuid: () => "artifact-1",
    now: () => new Date("2026-08-17T00:00:00.000Z"),
    ...overrides,
  };
}

describe("executeImageGeneration", () => {
  test("platform funding records cost without settling organization credits", async () => {
    const events: string[] = [];
    const bucket = new MemoryR2Bucket();
    const execute = createImageGenerationExecutor(dependencies(events));
    const outcome = await execute(
      requestInput(bucket, async () => ({ kind: "platform" as const })),
    );

    expect(outcome.images).toHaveLength(1);
    expect(events).toContain("provider");
    expect(events).toContain("history");
    expect(events).not.toContain("bill");
    expect(events.some((event) => event.startsWith("settle:"))).toBe(false);
    expect(events.some((event) => event.startsWith("direct-settle:"))).toBe(false);
    expect(events).not.toContain("settle-unknown");
  });

  test("persists one public artifact and durable history before exact settlement", async () => {
    const events: string[] = [];
    const bucket = new MemoryR2Bucket();
    const admission = successfulAdmission(events);
    const execute = createImageGenerationExecutor(dependencies(events));

    const outcome = await execute(
      requestInput(bucket, async () => {
        events.push("admit");
        return { kind: "organization", admission };
      }),
    );

    expect(outcome.images).toEqual([
      expect.objectContaining({
        generationId: "generation-1",
        url: "https://media.example.com/generations/images/org-1/user-1/artifact-1.png",
        mimeType: "image/png",
      }),
    ]);
    expect(bucket.objects.get("generations/images/org-1/user-1/artifact-1.png")).toEqual(PNG_BYTES);
    expect(events.filter((event) => event.startsWith("settle:"))).toEqual(["settle:0.02"]);
    expect(events.indexOf("dispatch")).toBeLessThan(events.indexOf("provider"));
    expect(events.indexOf("provider")).toBeLessThan(events.indexOf("r2-put"));
    expect(events.indexOf("r2-put")).toBeLessThan(events.indexOf("safety:media_generation_output"));
    expect(events.indexOf("history")).toBeLessThan(events.indexOf("bill"));
  });

  test("sanitizes provider failure, refunds admission, and leaves no artifact or history", async () => {
    const events: string[] = [];
    const bucket = new MemoryR2Bucket();
    const admission = successfulAdmission(events);
    const execute = createImageGenerationExecutor(
      dependencies(events, {
        getProvider: () => ({
          billingSource: "atlascloud",
          generate: async () => {
            events.push("provider");
            throw new Error("secret provider balance exhausted");
          },
        }),
      }),
    );

    const promise = execute(
      requestInput(bucket, async () => ({ kind: "organization", admission })),
    );
    await expect(promise).rejects.toMatchObject({
      status: 503,
      message: "Image generation is temporarily unavailable. Please try again shortly.",
    });
    expect(events).toContain("direct-settle:0");
    expect(events).not.toContain("history");
    expect(bucket.objects.size).toBe(0);
  });

  test("rolls back R2 and partial history when durable generation history fails", async () => {
    const events: string[] = [];
    const bucket = new MemoryR2Bucket();
    const admission = successfulAdmission(events);
    const execute = createImageGenerationExecutor(
      dependencies(events, {
        createGeneration: async () => {
          events.push("history");
          throw new Error("database unavailable");
        },
      }),
    );

    await expect(
      execute(requestInput(bucket, async () => ({ kind: "organization", admission }))),
    ).rejects.toThrow("database unavailable");
    expect(bucket.objects.size).toBe(0);
    expect(bucket.deleted).toHaveLength(1);
    expect(events).toContain("direct-settle:0");
    expect(events).not.toContain("bill");
  });

  test("does not dispatch a provider when organization-credit admission is refused", async () => {
    const events: string[] = [];
    const bucket = new MemoryR2Bucket();
    const execute = createImageGenerationExecutor(dependencies(events));

    await expect(
      execute(
        requestInput(bucket, async () => {
          throw new InsufficientCreditsError(0.02, 0, "test");
        }),
      ),
    ).rejects.toBeInstanceOf(InsufficientCreditsError);
    expect(events).not.toContain("provider");
    expect(bucket.objects.size).toBe(0);
  });

  test("uses conservative settlement if exact post-history billing becomes uncertain", async () => {
    const events: string[] = [];
    const bucket = new MemoryR2Bucket();
    const admission = successfulAdmission(events);
    const execute = createImageGenerationExecutor(
      dependencies(events, {
        billFlat: async () => {
          events.push("bill");
          throw new Error("settlement transport unavailable");
        },
      }),
    );

    const outcome = await execute(
      requestInput(bucket, async () => ({ kind: "organization", admission })),
    );
    expect(outcome.images).toHaveLength(1);
    expect(events).toContain("settle-unknown");
    expect(events).not.toContain("direct-settle:0");
    expect(bucket.objects.size).toBe(1);
  });

  test("returns the committed artifact when both exact and conservative settlement are offline", async () => {
    const events: string[] = [];
    const bucket = new MemoryR2Bucket();
    const admission = successfulAdmission(events);
    admission.settleUnknown = async () => {
      events.push("settle-unknown");
      throw new Error("reconciliation service unavailable");
    };
    const execute = createImageGenerationExecutor(
      dependencies(events, {
        billFlat: async () => {
          events.push("bill");
          throw new Error("settlement transport unavailable");
        },
      }),
    );

    const outcome = await execute(
      requestInput(bucket, async () => ({ kind: "organization", admission })),
    );

    expect(outcome.images).toHaveLength(1);
    expect(events).toContain("settle-unknown");
    expect(bucket.objects.size).toBe(1);
  });

  test("preserves the causal transaction error if admission release is offline", async () => {
    const events: string[] = [];
    const bucket = new MemoryR2Bucket();
    const admission = successfulAdmission(events);
    admission.settle = async (cost) => {
      events.push(`direct-settle:${cost}`);
      throw new Error("reservation release unavailable");
    };
    const execute = createImageGenerationExecutor(
      dependencies(events, {
        createGeneration: async () => {
          events.push("history");
          throw new Error("causal history failure");
        },
      }),
    );

    await expect(
      execute(requestInput(bucket, async () => ({ kind: "organization", admission }))),
    ).rejects.toThrow("causal history failure");
    expect(events).toContain("direct-settle:0");
    expect(bucket.objects.size).toBe(0);
  });

  test("fails closed before admission when provider credentials are absent", async () => {
    const events: string[] = [];
    const bucket = new MemoryR2Bucket();
    const execute = createImageGenerationExecutor(dependencies(events));
    const input = requestInput(bucket, async () => {
      throw new Error("admission must not run");
    });
    input.providerKeys = {};

    await expect(execute(input)).rejects.toBeInstanceOf(ApiError);
    expect(events).toEqual([]);
  });
});
